### PR TITLE
Added simple handle on edge cases (filling with empty pixels)

### PR DESCRIPTION
**Pull request by PoHaoChen**

### CODE REVIEW

**Comment by erendn** [comment]
This is missing 3 sides if you look at the output image.
1. For the top edge, you need to give output while taking the mid row the first time because `currentRow-1` is 0 there. That means the processor can and should output the corresponding pixel.
2. For the right edge, you need to give output when `currentCol` becomes 0 because `currentCol-1` will wrap around the image. I added some helper functions. You can use them.
3. For the bottom edge, you need to give output after taking all pixels. Don't immediately switch to the `done` state. Keep processing without taking any input and give the last edge as output.

**Comment by PoHaoChen** [comment]
I changed it and now it handles top, right, left. It seems like it just doesn't run enough cycles to perform operation for the bottom edge.

**Comment by erendn** [comment]
I know. I tried to explain it. You'll need to keep processing after you reach the last pixel. Anyways, I can do that.

**Comment by PoHaoChen** [comment]
I added 2 rows of extra cycles in tester script so now it fills bottom as well. I will also try other ways of filling after.

**Comment by erendn** [comment]
I realized you removed asserts and pixel checks. We have to keep those to make sure the code is doing what it is supposed to do. If an assert is failing, it doesn't mean the assert is wrong. It means your code is wrong. If an assert is failing, you must try to fix it not avoid it. Because of that, you didn't see that the output images are now shifted upwards. The reason for that is you "reset to start processing from top edge." You can't do this because it breaks the order of everything.

**Comment by erendn** [comment]
I fixed it for you. I also changed the logic so that we'll clamp the nearest pixels to match the library. Unfortunately, the library doesn't have an option to change the default "edge action." But it doesn't matter now since we're applying filter the same way and output images match perfectly.

**Pull request merged**
